DROP DATABASE remedi;
CREATE DATABASE remedi;
\c remedi

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  gluten BOOLEAN DEFAULT FALSE,
  vegan BOOLEAN DEFAULT FALSE,
  pescatarian BOOLEAN DEFAULT FALSE,
  halal BOOLEAN DEFAULT FALSE,
  keto BOOLEAN DEFAULT FALSE,
  dairy BOOLEAN DEFAULT FALSE,
  vegetarian BOOLEAN DEFAULT FALSE,
  kosher BOOLEAN DEFAULT FALSE,
  med BOOLEAN DEFAULT FALSE,
  paleo BOOLEAN DEFAULT FALSE,
  breakfast BOOLEAN DEFAULT FALSE,
  lunch BOOLEAN DEFAULT FALSE,
  dinner BOOLEAN DEFAULT FALSE,
  headache BOOLEAN DEFAULT FALSE,
  fatigue BOOLEAN DEFAULT FALSE,
  alert BOOLEAN DEFAULT FALSE,
  anxious BOOLEAN DEFAULT FALSE,
  bloated BOOLEAN DEFAULT FALSE,
  stomacheache BOOLEAN DEFAULT FALSE,
  low_energy BOOLEAN DEFAULT FALSE,
  lethargic BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS foods (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  gluten BOOLEAN DEFAULT FALSE,
  vegan BOOLEAN DEFAULT FALSE,
  pescatarian BOOLEAN DEFAULT FALSE,
  halal BOOLEAN DEFAULT FALSE,
  keto BOOLEAN DEFAULT FALSE,
  dairy BOOLEAN DEFAULT FALSE,
  vegetarian BOOLEAN DEFAULT FALSE,
  kosher BOOLEAN DEFAULT FALSE,
  med BOOLEAN DEFAULT FALSE,
  paleo BOOLEAN DEFAULT FALSE,
  breakfast BOOLEAN DEFAULT FALSE,
  lunch BOOLEAN DEFAULT FALSE,
  dinner BOOLEAN DEFAULT FALSE,
  headache BOOLEAN DEFAULT FALSE,
  fatigue BOOLEAN DEFAULT FALSE,
  alert BOOLEAN DEFAULT FALSE,
  bloated BOOLEAN DEFAULT FALSE,
  anxious BOOLEAN DEFAULT FALSE,
  stomacheache BOOLEAN DEFAULT FALSE,
  low_energy BOOLEAN DEFAULT FALSE,
  lethargic BOOLEAN DEFAULT FALSE
);
